export type Product = {
  id: number;
  name: string;
  category: 'Stuffed Toys' | 'Keychains' | 'BTS Bombs' | 'Miniatures' | 'Animated Pictures';
  price: number;
  image: string;
  rating: number;
  popularity: number;
  'data-ai-hint': string;
  description: string;
};

export const products: Product[] = [
  {
    id: 1,
    name: 'Plush Chimmy Toy',
    category: 'Stuffed Toys',
    price: 29.99,
    image: 'https://m.media-amazon.com/images/I/51lNu0OWpwL._SX300_SY300_QL70_FMwebp_.jpg',
    rating: 4.8,
    popularity: 95,
    'data-ai-hint': 'plush toy',
    description: "Bring home the adorable Chimmy, designed by Jimin. This soft and cuddly plush toy is the perfect companion for any ARMY.",
  },
  {
    id: 2,
    name: 'Cooky Keychain',
    category: 'Keychains',
    price: 12.50,
    image: 'https://picsum.photos/400/400?random=2',
    rating: 4.9,
    popularity: 98,
    'data-ai-hint': 'keychain accessory',
    description: "Take the energetic Cooky with you everywhere. This durable keychain, designed by Jungkook, adds a touch of Bangtan to your keys or bag.",
  },
  {
    id: 3,
    name: 'Official Light Stick Ver.4',
    category: 'BTS Bombs',
    price: 55.00,
    image: 'https://picsum.photos/400/400?random=3',
    rating: 5.0,
    popularity: 100,
    'data-ai-hint': 'light stick',
    description: "The essential item for any concert-goer. The official Map of the Soul Special Edition ARMY Bomb connects to concert seating for a unified ocean of light.",
  },
  {
    id: 4,
    name: 'TinyTan Figure Set',
    category: 'Miniatures',
    price: 79.99,
    image: 'https://picsum.photos/400/400?random=4',
    rating: 4.7,
    popularity: 92,
    'data-ai-hint': 'figure set',
    description: "Collect all seven members of BTS in their adorable TinyTan forms. These detailed miniatures are perfect for display on your desk or shelf.",
  },
  {
    id: 5,
    name: 'BT21 Animated Art Frame',
    category: 'Animated Pictures',
    price: 45.00,
    image: 'https://picsum.photos/400/400?random=5',
    rating: 4.6,
    popularity: 88,
    'data-ai-hint': 'art frame',
    description: "A magical art frame that brings BT21 characters to life. This digital frame displays a loop of cute animations, perfect for any room.",
  },
  {
    id: 6,
    name: 'RJ Alpaca Cushion',
    category: 'Stuffed Toys',
    price: 34.99,
    image: 'https://picsum.photos/400/400?random=6',
    rating: 4.9,
    popularity: 96,
    'data-ai-hint': 'cushion pillow',
    description: "Rest your head on this incredibly soft and kind RJ cushion. Designed by Jin, this alpaca cushion is perfect for naps and decoration.",
  },
  {
    id: 7,
    name: 'Shooky Suga Figurine',
    category: 'Miniatures',
    price: 18.99,
    image: 'https://picsum.photos/400/400?random=7',
    rating: 4.8,
    popularity: 85,
    'data-ai-hint': 'figurine character',
    description: "The mischievous and fun-loving Shooky, designed by Suga. This high-quality figurine captures the playful spirit of the magical cookie.",
  },
  {
    id: 8,
    name: 'Tata Heart Pillow',
    category: 'Stuffed Toys',
    price: 32.00,
    image: 'https://picsum.photos/400/400?random=8',
    rating: 4.9,
    popularity: 94,
    'data-ai-hint': 'heart pillow',
    description: "A super-soft, heart-shaped pillow of the curious alien Tata. Designed by V, it's a quirky and lovable addition to any collection.",
  },
   {
    id: 9,
    name: 'Van Space Robot Keychain',
    category: 'Keychains',
    price: 14.00,
    image: 'https://picsum.photos/400/400?random=9',
    rating: 4.7,
    popularity: 89,
    'data-ai-hint': 'robot keychain',
    description: "The guardian space robot Van, who protects BT21. This sleek and modern keychain represents the unity of ARMYs worldwide.",
  },
   {
    id: 10,
    name: 'Mang Dance Practice Figure',
    category: 'Miniatures',
    price: 22.50,
    image: 'https://picsum.photos/400/400?random=10',
    rating: 4.8,
    popularity: 91,
    'data-ai-hint': 'dance figure',
    description: "Capture the dynamic dance moves of Mang, J-Hope's creation. This figure shows Mang in a signature dance pose, full of energy and hope.",
  },
   {
    id: 11,
    name: 'Koya Reading Lamp',
    category: 'Animated Pictures',
    price: 38.00,
    image: 'https://picsum.photos/400/400?random=11',
    rating: 4.9,
    popularity: 90,
    'data-ai-hint': 'reading lamp',
    description: "A gentle reading lamp featuring the sleepy but smart Koya. Designed by RM, it provides a soft glow for your late-night reading sessions.",
  },
   {
    id: 12,
    name: 'BTS Logo Enamel Pin',
    category: 'Keychains',
    price: 9.99,
    image: 'https://picsum.photos/400/400?random=12',
    rating: 5.0,
    popularity: 99,
    'data-ai-hint': 'enamel pin',
    description: "The iconic BTS logo as a high-quality enamel pin. A subtle yet powerful way to show your ARMY pride on any jacket, bag, or pinboard.",
  },
];
